language: python

python:
  - "2.7"
env:
  global:
    secure: "bZtwY7NW6DRPzvhHMIw1vvxYlb5xiu4s9MIDzYO3fQbwjGttc5IMN49CGfpTwoGxXOVP4U+VBMu2plo3dVzLb4Mkdyplm8psASlSnZewzujmAC0jr1qwHBVEnTUCFABZsss2bYmf27WOdIlFbbrjdW/mDnaH4Ud4HbZHsukUKfs="

install:
  - pip install -r requirements.txt

before_script:
  - git config --global user.email "libsora25@gmail.com"
  - git config --global user.name "Travis"

script:
  - nosetests --with-cov --cov-config .coveragerc --cov-report term --cov mirai tests/
  - git clone https://github.com/shipduck/stop-game-prior-censorship.git output --branch gh-pages --depth 5
  - python freeze.py
  - cp -r build/* output
  - echo "stop-game-prior-censorship.libsora.so" > output/CNAME

after_success:
  - cd output
  - git add -f .
  - git commit -a -m "add new site content" --allow-empty
  - git push https://${GH_TOKEN}@github.com/shipduck/stop-game-prior-censorship.git gh-pages --quiet
  - cd ..
  - coveralls

notifications:
  email: false

